import {
  Column,
  CreateDateColumn,
  Entity,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';

import { Task } from './task.entity';

/**
 * Represents a step associated with a task.
 * Generated by the IA and can be edited by the user
 */
@Entity()
export class Step {
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * Human-readable text that describes what the step is about.
   */
  @Column()
  content: string;

  /**
   * Position of the step inside its task.
   */
  @Column({ default: 0 })
  position: number;

  /**
   * Marks if the step is fully completed
   */
  @Column({ default: false })
  completed: boolean;

  /**
   * Task associated with this step
   */
  @ManyToOne(() => Task, (task) => task.steps, { onDelete: 'CASCADE' })
  task: Task;

  @CreateDateColumn()
  createdAt: Date;
}
